# docker-compose-auth.yml
version: '3'

services:
  oidc-auth:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oidc-auth
    command:
      - --provider=oidc
      - --client-id=your-client-id
      - --client-secret=your-client-secret
      - --oidc-issuer-url=https://your-keycloak-server/auth/realms/your-realm
      - --cookie-secret=your-cookie-secret
      - --email-domain=*
      - --upstream=static://200
      - --http-address=0.0.0.0:4180
      - --redirect-url=https://your-traefik-ip/webapp/oauth2/callback
      - --skip-provider-button=true
      - --cookie-secure=true
      - --cookie-domains=*
      - --whitelist-domain=your-traefik-ip
      - --cookie-path=/
      - --path-scope=/webapp
      - --set-xauthrequest=true
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
